import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from '../../../environments/environment';
import 'rxjs/add/operator/map';

const translationsSp = {
  'Error:': 'Error:',
  'Try': 'Pruebe',
  'Files': 'Ficheros',
  'API': 'API',
  'About': 'Acerca de',
  'Logout': 'Desconectar',
  'Created with ♥ by': 'Creado con ♥ por',
  'Loading...': 'Cargando...',
  'Loading': 'Cargando',
  'Date': 'Fecha',
  'from': 'desde',
  'to': 'hasta',
  'Anger': 'Enfado',
  'anger': 'enfado',
  'Filter': 'Filtro',
  'Reset Filter': 'Reiniciar filtro',
  'Export to CSV': 'Exportar a CSV',
  'Batch Id': 'Id de lote',
  'Batches': 'De lote',
  'Name': 'Nombre',
  'Uploaded': 'Cargado',
  'Duration': 'Duración',
  'Emotion': 'Emoción',
  'emotion': 'emoción',
  'Beta': 'Beta',
  'File details': 'Detalles de fichero',
  'Refresh': 'Refrescar',
  'Delete': 'Borrar',
  'Details': 'Detalles',
  'Back': 'Atrás',
  'Fit into window': 'Ajustar a la ventana',
  'Happiness': 'Alegría',
  'Sadness': 'Tristeza',
  'Neutral': 'Neutro',
  'Dominant emotion detected': 'Emoción dominante detectada',
  'Male': 'Masculino',
  'Female': 'Femenino',
  'Teen': 'Adolescente',
  'Adult': 'Adulto',
  'Senior': 'Anciano',
  'Are you agree with the result?': '¿Está de acuerdo con el resultado?',
  'Yes': 'Sí',
  'No': 'No',
  'Thank you for reply!': '¡Gracias por su respuesta!',
  'Check another record': 'Comprobar otra grabación',
  'Anger level': 'Nivel de enfado',
  'Make a trial record or upload a file': 'Haga una prueba, grabe o cargue un fichero',
  'Start': 'Comenzar',
  'Upload': 'Cargar',
  'Record': 'Grabar',
  'UPLOAD': 'Cargar',
  'RECORD': 'Grabar',
  'Recording': 'Grabando',
  'You can upload only one file a time': 'Los ficheros se cargan de uno en uno',
  'Drop file here or click to browse': 'Suelte el fichero aquí o haga clic para abrir el explorador',
  'Discard': 'Descartar',
  'Attach': 'Añadir',
  'Play': 'Reproducir',
  'Change': 'Cambiar',
  'Results': 'Resultados',
  'Sign in': 'Conéctese',
  'Username': 'Nombre de usuario',
  'Password': 'Contraseña',
  'Remember me': 'Recuérdeme',
  "Don't have an account?": '¿No tiene una cuenta?',
  'Sign Up': 'Regístrese',
  'First name': 'Nombre',
  'Last name': 'Apellido',
  'Email': 'Correo electrónico',
  'Access Code': 'Código de acceso',
  'I have read the terms and conditions and privacy policy and agree to them': 'He leído los términos y condiciones, así como la política de privacidad y estoy de acuerdo',
  'I agree that my data is used, saved and processed by the NeoSound OU for the utilization of my account.': 'Estoy de acuerdo con que mis datos sean utilizados, guardados y procesados por NeoSound OU para la utilización de mi cuenta.',
  'SIGN UP': 'REGÍSTRESE',
  'Already have an account?': '¿Ya tiene una cuenta?',
  'Login': 'Inicie sesión',
  'All': 'Todos',
  'Terms of Use': 'Términos de Uso',
  'Selected files total count': 'Cantidad total de archivos seleccionados',
  '0 Files': '0 archivos',
  'Avg.Pause': 'Pausa media',
  'Search': 'Buscar',
  'Music': 'Música',
  'Merged': 'Fusionado',
  'Probs test': 'Problemas test',
  'Text': 'Texto',
  'See details': 'Ver detalles',
  'here': 'aquí',
  'Sad': 'Triste',
  'Happy': 'Feliz',
  'Total files on page': 'Total de archivos en la página',
  'out of': 'de',
  'previous': 'anterior',
  'next': 'siguiente',
  'On-hold': 'En espera',
  'Wrong credentials': 'Credenciales incorrectas',
  'Batch': 'De lote',
  'Total number of cells': 'Número total de celdas',
  'Cells with pauses higher than threshold': 'Celdas con pausas superiores al umbral.',
  'FILES': 'ARCHIVOS',
  'DETAILS': 'DETALLES',
  'Min.': 'Min.',
  'Max.': 'Max.',
  'Avg.': 'promedio',
  'Med.': 'Medio',
};
const translationsRu = {
  'Error:': 'Ошибка:',
  'Try': 'Попробовать',
  'Files': 'Файлы',
  'API': 'API',
  'About': 'О Нас',
  'Logout': 'Выход',
  'Created with ♥ by': 'Сделано с ♥ ',
  'Loading...': 'Загрузка...',
  'Loading': 'Загрузка',
  'Date': 'Дата',
  'from': 'от',
  'to': 'до',
  'Anger': 'Агрессия',
  'anger': 'агрессия',
  'Filter': 'Фильтр',
  'Reset Filter': 'Сбросить фильтр',
  'Export to CSV': 'Экспорт в CSV',
  'Batch Id': 'Батч (агент)',
  'Batches': 'Батчи (агенты)',
  'Name': 'Имя',
  'Uploaded': 'Загружено',
  'Duration': 'Длительность',
  'Emotion': 'Эмоция',
  'emotion': 'эмоция',
  'Beta': 'Бета',
  'File details': 'Подробности',
  'Refresh': 'Обновить',
  'Delete': 'Удалить',
  'Details': 'Подробности',
  'Back': 'Назад',
  'Fit into window': 'Вписать в окно',
  'Happiness': 'Счастье',
  'Sadness': 'Грусть',
  'Neutral': 'Нейтрально',
  'Dominant emotion detected': 'Доминирующая эмоция определена',
  'Male': 'Мужской',
  'Female': 'Женский',
  'Teen': 'Подросток',
  'Adult': 'Взрослый',
  'Senior': 'Пожилой',
  'Are you agree with the result?': 'Вы согласны с результатом?',
  'Yes': 'Да',
  'No': 'Нет',
  'Thank you for reply!': 'Спасибо за ответ!',
  'Check another record': 'Попробовать другую запись',
  'Anger level': 'Сила эмоций',
  'Make a trial record or upload a file': 'Сделайте пробную запись или загрузите файл',
  'Start': 'Начать',
  'Upload': 'Загрузка',
  'Record': 'Запись',
  'UPLOAD': 'ЗАГРУЗКА',
  'RECORD': 'ЗАПИСЬ',
  'Recording': 'Идет запись',
  'You can upload only one file a time': 'Возможно загрузить только 1 файл за раз',
  'Drop file here or click to browse': 'Перетащите файлы сюда или нажмите для выбора',
  'Discard': 'Отменить',
  'Attach': 'Добавить',
  'Play': 'Проиграть',
  'Change': 'Заменить',
  'Results': 'Результаты',
  'Sign in': 'Войти',
  'Username': 'Имя пользователя',
  'Password': 'Пароль',
  'Remember me': 'Запомнить меня',
  "Don't have an account?": 'Нет аккаунта?',
  'Sign Up': 'Зарегистрироваться',
  'First name': 'Имя',
  'Last name': 'Фамилия',
  'Email': 'Email',
  'Access Code': 'Код доступа',
  'I have read the terms and conditions and privacy policy and agree to them': 'Я прочитал(а) правила использования и согласен с ними',
  'I agree that my data is used, saved and processed by the NeoSound OU for the utilization of my account.': 'Я согласен(на) с тем, что мои данные используются, хранятся и обрабатываются NeoSound Intelligence B.V. для нужд моей учетной записи',
  'SIGN UP': 'ЗАРЕГИСТРИРОВАТЬСЯ',
  'Already have an account?': 'Уже есть аккаунт?',
  'Login': 'Войти',
  'All': 'Все',
  'Terms of Use': 'Правила использования',
  'Selected files total count': 'Количество выбранных файлов',
  '0 Files': '0 Файлов',
  'Avg.Pause': 'Сред.Пауза',
  'Search': 'Поиск',
  'Music': 'Музыка',
  'Merged': 'Объединен.',
  'Probs test': 'Тест проблем',
  'Text': 'Текст',
  'See details': 'Детали',
  'here': 'тут',
  'Sad': 'Грусть',
  'Happy': 'Счастье',
  'Total files on page': 'Всего файлов на странице',
  'out of': 'из',
  'previous': 'пред.',
  'next': 'след.',
  'On-hold': 'В ожидании',
  'Wrong credentials': 'Неправильные учетные данные',
  'Batch': 'Батч (агент)',
  'Total number of cells': 'Общее количество записей',
  'Cells with pauses higher than threshold': 'Записи с паузами выше порога',
  'FILES': 'ФАЙЛЫ',
  'DETAILS': 'ПОДРОБНОСТИ',
  'Min.': 'Mин.',
  'Max.': 'Mакс.',
  'Avg.': 'Средн.',
  'Med.': 'Медиана',
};

@Injectable()
export class LanguageService {

  constructor(
  ) { }

  checkLanguage(ln) {
    const lang = localStorage.getItem('lang');
    return lang && (lang === ln) || !lang && ln === 'en';
  }

  getLanguage() {
    const lang = localStorage.getItem('lang');
    return lang || !lang && 'en';
  }

  static t(text) {
    const lang = localStorage.getItem('lang');
    const current =  lang || !lang && 'en';

    if (current === 'en') {
      return text;
    }
    if (current === 'sp') {
      return translationsSp[text] || text;
    }
    if (current === 'ru') {
      return translationsRu[text] || text;
    }
  }
}
